#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 23 13:11:34 CEST 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 370952dc9ab94906a14a4cd41398f151 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mega_adder_tb_behav xil_defaultlib.mega_adder_tb -log elaborate.log"
xelab -wto 370952dc9ab94906a14a4cd41398f151 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot mega_adder_tb_behav xil_defaultlib.mega_adder_tb -log elaborate.log

