#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 09 12:44:02 CEST 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f5d16f418101419fb755cd2f50c9db87 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L bftlib -L unisims_ver -L unimacro_ver -L secureip --snapshot bft_tb_behav xil_defaultlib.bft_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto f5d16f418101419fb755cd2f50c9db87 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L bftlib -L unisims_ver -L unimacro_ver -L secureip --snapshot bft_tb_behav xil_defaultlib.bft_tb xil_defaultlib.glbl -log elaborate.log

