#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Sep 09 12:44:14 CEST 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim bft_tb_behav -key {Behavioral:sim_1:Functional:bft_tb} -tclbatch bft_tb.tcl -log simulate.log"
xsim bft_tb_behav -key {Behavioral:sim_1:Functional:bft_tb} -tclbatch bft_tb.tcl -log simulate.log

